// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCgD7fVICfofulgfLecZF2bCNK_3NHMfsI',
    appId: '1:876574075071:web:d7b9d402417106b88a7e0a',
    messagingSenderId: '876574075071',
    projectId: 'madam-d8cd5',
    authDomain: 'madam-d8cd5.firebaseapp.com',
    storageBucket: 'madam-d8cd5.appspot.com',
    measurementId: 'G-6MCLTD06VF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDwSzk8500Q7qGBXBYzU4AU2MytptfJ9ZI',
    appId: '1:876574075071:android:fc96bb9c4766b9fa8a7e0a',
    messagingSenderId: '876574075071',
    projectId: 'madam-d8cd5',
    storageBucket: 'madam-d8cd5.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCfJ1lzMwo1azBSUIoNjyyDDvrqm7bLxx4',
    appId: '1:876574075071:ios:429fe0fd1645e1548a7e0a',
    messagingSenderId: '876574075071',
    projectId: 'madam-d8cd5',
    storageBucket: 'madam-d8cd5.appspot.com',
    iosClientId: '876574075071-9hfc799vdkqdqma68917l07kbn6kmrmi.apps.googleusercontent.com',
    iosBundleId: 'com.example.madamAdmin',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCfJ1lzMwo1azBSUIoNjyyDDvrqm7bLxx4',
    appId: '1:876574075071:ios:429fe0fd1645e1548a7e0a',
    messagingSenderId: '876574075071',
    projectId: 'madam-d8cd5',
    storageBucket: 'madam-d8cd5.appspot.com',
    iosClientId: '876574075071-9hfc799vdkqdqma68917l07kbn6kmrmi.apps.googleusercontent.com',
    iosBundleId: 'com.example.madamAdmin',
  );
}
